# Generated by Django 3.1 on 2020-08-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myweb',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
